ALTER TABLE `userSubscriptions`
  ADD COLUMN `planTier` ENUM('free','essential','ultra') NOT NULL DEFAULT 'free' AFTER `planCode`,
  ADD COLUMN `monthlyNarrativeCreditLimit` INT NOT NULL DEFAULT 5000 AFTER `creditAllowance`,
  ADD COLUMN `monthlyNarrativeCreditsUsed` INT NOT NULL DEFAULT 0 AFTER `monthlyNarrativeCreditLimit`,
  ADD COLUMN `monthlyNarrativeCreditsReserved` INT NOT NULL DEFAULT 0 AFTER `monthlyNarrativeCreditsUsed`,
  ADD COLUMN `extraNarrativeCredits` INT NOT NULL DEFAULT 0 AFTER `monthlyNarrativeCreditsReserved`,
  ADD COLUMN `extraNarrativeCreditsReserved` INT NOT NULL DEFAULT 0 AFTER `extraNarrativeCredits`,
  ADD COLUMN `billingCycleStart` TIMESTAMP NULL AFTER `extraNarrativeCreditsReserved`,
  ADD COLUMN `billingCycleEnd` TIMESTAMP NULL AFTER `billingCycleStart`;

CREATE TABLE `generationJobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `publicId` VARCHAR(64) NOT NULL,
  `idempotencyKey` VARCHAR(255) NOT NULL,
  `userId` INT NOT NULL,
  `workId` INT NULL,
  `draftId` INT NULL,
  `chapterId` INT NULL,
  `outputChapterId` INT NULL,
  `action` ENUM('generate','regenerate','localized_edit') NOT NULL DEFAULT 'generate',
  `generationMode` ENUM('standard','premium') NOT NULL DEFAULT 'standard',
  `planTier` ENUM('free','essential','ultra') NOT NULL DEFAULT 'free',
  `engine` ENUM('current','open_source_4090','open_source_h100','openai_instant','openai_thinking') NOT NULL DEFAULT 'current',
  `fallbackEngine` ENUM('current','open_source_4090','open_source_h100','openai_instant','openai_thinking') NULL,
  `status` ENUM('queued','preparing','generating','finalizing','completed','failed','canceled') NOT NULL DEFAULT 'queued',
  `progressMessage` VARCHAR(500) NOT NULL,
  `inputSnapshot` MEDIUMTEXT NULL,
  `outputText` MEDIUMTEXT NULL,
  `draftVersion` INT NULL,
  `chapterVersion` INT NULL,
  `requestedMaxOutputWords` INT NOT NULL DEFAULT 0,
  `generatedWordCount` INT NOT NULL DEFAULT 0,
  `reservedCredits` INT NOT NULL DEFAULT 0,
  `reservedMonthlyCredits` INT NOT NULL DEFAULT 0,
  `reservedExtraCredits` INT NOT NULL DEFAULT 0,
  `confirmedCredits` INT NOT NULL DEFAULT 0,
  `confirmedMonthlyCredits` INT NOT NULL DEFAULT 0,
  `confirmedExtraCredits` INT NOT NULL DEFAULT 0,
  `releasedCredits` INT NOT NULL DEFAULT 0,
  `attempts` INT NOT NULL DEFAULT 0,
  `maxAttempts` INT NOT NULL DEFAULT 2,
  `lockedAt` TIMESTAMP NULL,
  `lockedBy` VARCHAR(120) NULL,
  `lockExpiresAt` TIMESTAMP NULL,
  `startedAt` TIMESTAMP NULL,
  `completedAt` TIMESTAMP NULL,
  `canceledAt` TIMESTAMP NULL,
  `errorCode` VARCHAR(120) NULL,
  `errorMessage` TEXT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_generationJobs_publicId` (`publicId`),
  UNIQUE KEY `uniq_generationJobs_user_idempotency` (`userId`, `idempotencyKey`),
  KEY `idx_generationJobs_user_status` (`userId`, `status`),
  KEY `idx_generationJobs_work_status` (`workId`, `status`),
  KEY `idx_generationJobs_lock` (`status`, `lockExpiresAt`)
);

CREATE TABLE `generationCostLogs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jobId` INT NOT NULL,
  `publicJobId` VARCHAR(64) NOT NULL,
  `userId` INT NOT NULL,
  `workId` INT NULL,
  `engine` VARCHAR(80) NOT NULL,
  `fallbackEngine` VARCHAR(80) NULL,
  `startedAt` TIMESTAMP NULL,
  `finishedAt` TIMESTAMP NULL,
  `durationSeconds` INT NOT NULL DEFAULT 0,
  `inputWordCount` INT NOT NULL DEFAULT 0,
  `outputWordCount` INT NOT NULL DEFAULT 0,
  `estimatedCostUsd` VARCHAR(32) NULL,
  `status` ENUM('success','failed','canceled') NOT NULL,
  `errorCode` VARCHAR(120) NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_generationCostLogs_jobId` (`jobId`),
  KEY `idx_generationCostLogs_userId` (`userId`)
);

CREATE TABLE `generationUsageLedger` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jobId` INT NOT NULL,
  `publicJobId` VARCHAR(64) NOT NULL,
  `userId` INT NOT NULL,
  `workId` INT NULL,
  `source` ENUM('monthly','extra') NOT NULL,
  `type` ENUM('reserve','confirm','release','refund','adjustment') NOT NULL,
  `amount` INT NOT NULL,
  `balanceAfter` INT NULL,
  `reason` VARCHAR(255) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_generationUsageLedger_jobId` (`jobId`),
  KEY `idx_generationUsageLedger_userId` (`userId`)
);
